cmake_minimum_required(VERSION 3.10)
project(dvl_cpp_probe)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(marine_acoustic_msgs REQUIRED)
add_executable(dvl_cpp_probe src/dvl_cpp_probe.cpp)
target_link_libraries(dvl_cpp_probe PRIVATE rclcpp::rclcpp marine_acoustic_msgs::marine_acoustic_msgs)
install(TARGETS dvl_cpp_probe DESTINATION lib/${PROJECT_NAME})
ament_package()
